### ISSUE TITLE
Package.swift is broken

### ISSUE THREAD

**Issue by rderik** [richiercyrus/Venator-Swift#3]
Found a few problems with the `Package.swift`:

+ The `Package.swift` file doesn't contain all the information to build and run Venator from the SPM (Swift Package Manager).
+ The `Venator` target is missing the dependencies on Swift Argument Parser.

**Comment by rderik** [comment]
@richiercyrus You can assign this issue to me. I already have a fix. I'll create a pull request soon.

**Comment by richiercyrus** [comment]
Thanks for this!
